Resources:
  CognitoUserPoolAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerResultTtlInSeconds: 10
      IdentitySource: method.request.header.Authorization
      Name: ${env:AppName}-${env:Stage}-CognitoAuthorizer
      RestApiId:
        Ref: "ApiGatewayRestApi"
      Type: COGNITO_USER_POOLS
      ProviderARNs:
        - {
          "Fn::Join":
          [
           "",
           [
             "arn:aws:cognito-idp:",
             {
               Ref: "AWS::Region"
             },
             ":",
             {Ref: "AWS::AccountId"},
             ":userpool/",
             Ref: CognitoUserPoolMyUserPool,
           ],
          ],
        }

        #Print
Outputs:
  CognitoUserPoolAuthorizerName:
    Value:
      Ref: CognitoUserPoolAuthorizer
        